#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/usuarios

###

POST http://localhost:3333/usuarios
Content-Type: application/json

{
    "nome": "ORELHA",
    "email": "12345",
    "senha": "COMUM",
    "cpf": "11122233344",
    "telefone": "1234567900",
    "endereco": "asdasd"
}

###

PUT http://localhost:3333/usuarios/f15beabf-842f-4a20-b866-5350bfda6d6b
Content-Type: application/json

{
    "nome": "ORELHA",
    "email": "12345",
    "senha": "BORGES",
    "cpf": "11122233344",
    "telefone": "1234567900",
    "endereco": "asdasd"
}

###

DELETE http://localhost:3333/usuarios/7464b07f-f254-4960-bcf9-3e81bd3a9b6a
