
#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###


POST http://localhost:3333/login
Content-Type: application/json

{
    "email": "aaaa@gmail.com",
    "senha": "123"
}

###



//USUARIO
GET http://localhost:3333/usuarios

###

POST http://localhost:3333/usuarios
Content-Type: application/json

{
    "nome": "ORELHA",
    "email": "adm@gmail.com",
    "senha": "123",
    "cpf": "11122233344",
    "telefone": "1234567900",
    "endereco": "asdasd"
}

###

PUT http://localhost:3333/usuarios/b3d6a362-5211-4d85-b2eb-d7a5f5bf3dca
Content-Type: application/json

{
    "nome": "ORELHA",
    "email": "adm@gmail.com",
    "senha": "adm123",
    "cpf": "11122233344",
    "telefone": "1234567900",
    "endereco": "asdasd"
}

###

DELETE http://localhost:3333/usuarios/55e0c849-22c0-4287-a76a-d1529438e203



//PRODUTO
###

GET http://localhost:3333/produtos
###

POST http://localhost:3333/produtos
Content-Type: application/json

{
    "nome": "Camiseta",
    "tamanho": "G",
    "valor": "189",
    "quantidade": "50",
    "descricao": "Camiseta"
}

###

PUT http://localhost:3333/produtos/5f411b7c-70ae-4a67-856a-d3e1ea34b1d8
Content-Type: application/json

{
    "nome": "Camiseta",
    "tamanho": "G",
    "valor": "189",
    "quantidade": "55",
    "descricao": "Camiseta"
}

###
GET http://localhost:3333/produtosCatalogo/1
Content-Type: application/json

###

DELETE http://localhost:3333/produtos/1
